version: "3.7"
services:
  api_service:
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mariadb
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/ontdekstation013?allowPublicKeyRetrieval=true

    volumes:
      - .m2:/root/.m2

  mariadb:
    image: "mariadb:lts"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: ontdekstation013
      MYSQL_USER: ontdekstation
      MYSQL_PASSWORD: ontdekstation013
      MYSQL_ROOT_PASSWORD: ontdekstation
    volumes:
      - "./dump-ontdekstation013.sql:/docker-entrypoint-initdb.d/1.sql"

networks:
  springapimysql-net: