name: Build and Test

on:
  push:
    branches: ["s3nj23_dev"]
  pull_request:
    branches: ["s3nj23_dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn package --file pom.xml -DskipTests
        working-directory: ClimateChecker

      - name: Test
        run: mvn -Dmaven.test.failure.ignore=true test
        working-directory: ClimateChecker

      - name: Report
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: ClimateChecker/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
